### ISSUE TITLE
Why EX-RHCR's throughput is lower than RHCR's？

### ISSUE THREAD

**Issue by zhx0506** [NitzanMadar/exPBS-exRHCR#1]
Hello, first of all, thank you to your team for your contribution to EX-RHCR. I have a question regarding the throughput performance. In the original RHCR paper, the throughput reached 2.33 with 60 agents on the warehouse map. However, I found that EX-RHCR only achieves about 1.5. Could you explain the reason for this discrepancy?

**Comment by NitzanMadar** [comment]
Hi,

Thank you for your question and for your interest in the paper.

It appears that the discrepancy you're observing may be due to an incorrect comparison. Here are some key factors to consider:

* **Codebase Differences:** The two implementations are based on different codebases, which can lead to variations in performance.
* **Hardware Differences:** The experiments in the original RHCR paper were conducted on a different hardware setup. Differences in computing power can significantly impact results.
* **Task Assignment Mechanism and Testing Scenarios:** The tasks, task assignment (TA) mechanism, and tests themselves differ between exRHCR and RHCR, resulting in incomparable evaluations.
* **Throughput Measurement:** The method of measuring throughput may vary slightly between the two implementations, which can affect the comparability of the results.
* **Map Implementation:** There are also differences in the map setups. For example, RHCR utilizes a directed version of the sorting center map.

Additionally, the experiments in the paper were conducted with 100 or more agents, whereas it seems your evaluation involved 60 agents. If you ran these tests independently, I would recommend ensuring that the codebase (including implementation, TA mechanism, and performance measurement) is consistent across both systems for a fair comparison. Please also consider the parameters used in exRHCR when conducting your evaluation.

Feel free to reach out via email if you have further questions.
